// Generated by CoffeeScript 1.6.3
(function() {
  var HTTP_PORT, http, url;

  HTTP_PORT = 8008;

  http = require('http');

  url = require('url');

  http.createServer(function(req, res) {
    console.log("" + req.socket.remoteAddress + ":", url.parse(req.url, true).query);
    res.writeHead(204, "");
    return res.end();
  }).listen(HTTP_PORT);

}).call(this);
